### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by rsaf** [jenish4096/express-mongo-elasticsearch#7]
Thanks for the  amazing boiller plate. It's exactly what I have been looking for. 

But after following the instructions on the readme.md. I successfully setup the project with docker. But when I make the following request to search users. I get and unkown error:

POST REQUEST (curl copied from postman)

`curl --location --request POST 'localhost:3000/v1/employees/list' \
--header 'Content-Type: application/json' \
--data-raw '{
	"term":"riddell",
	"fieldToSort":"lastName",
	"order":"ASC",
	"page":1,
	"perPage":10
}'
`

RESPONSE BODY WITH ERROR

`
{
    "code": 400,
    "message": "[query_shard_exception] failed to create query: {\n  \"multi_match\" : {\n    \"query\" : \"riddell\",\n    \"fields\" : [\n      \"address^1.0\",\n      \"age^1.0\",\n      \"dateOfJoining^1.0\",\n      \"designation^1.0\",\n      \"firstName^1.0\",\n      \"gender^1.0\",\n      \"lastName^1.0\",\n      \"maritalStatus^1.0\",\n      \"salary^1.0\"\n    ],\n    \"type\" : \"phrase_prefix\",\n    \"operator\" : \"OR\",\n    \"slop\" : 0,\n    \"prefix_length\" : 0,\n    \"max_expansions\" : 50,\n    \"zero_terms_query\" : \"NONE\",\n    \"auto_generate_synonyms_phrase_query\" : true,\n    \"fuzzy_transpositions\" : true,\n    \"boost\" : 1.0\n  }\n}, with { index_uuid=\"v5eoZN8oQlSSWzRo97hV0g\" & index=\"employees\" }",
    "stack": "Error: [query_shard_exception] failed to create query: {\n  \"multi_match\" : {\n    \"query\" : \"riddell\",\n    \"fields\" : [\n      \"address^1.0\",\n      \"age^1.0\",\n      \"dateOfJoining^1.0\",\n      \"designation^1.0\",\n      \"firstName^1.0\",\n      \"gender^1.0\",\n      \"lastName^1.0\",\n      \"maritalStatus^1.0\",\n      \"salary^1.0\"\n    ],\n    \"type\" : \"phrase_prefix\",\n    \"operator\" : \"OR\",\n    \"slop\" : 0,\n    \"prefix_length\" : 0,\n    \"max_expansions\" : 50,\n    \"zero_terms_query\" : \"NONE\",\n    \"auto_generate_synonyms_phrase_query\" : true,\n    \"fuzzy_transpositions\" : true,\n    \"boost\" : 1.0\n  }\n}, with { index_uuid=\"v5eoZN8oQlSSWzRo97hV0g\" & index=\"employees\" }\n    at respond (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/src/app/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/src/app/node_modules/lodash/lodash.js:4949:19)\n    at IncomingMessage.emit (events.js:326:22)\n    at endReadableNT (_stream_readable.js:1241:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
`

I'm not sure what is causing the error. When I pass an empty search term (eg: "term":"") in my request, there is no error. but I only get the count as a response. And no employee data.

**Comment by rsaf** [comment]
I found the issue in the code and fixed it. thanks.

The mutli_match block in elastic search was the issue.
